[package]
edition = "2021"
name = "status-mail"
version = "0.1.0"

[dependencies]
argh = "0.1"
anyhow = "1"
humansize = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
nix = { version = "0.26", features = ["fs"] }
zbus = "3"
